### ISSUE TITLE
关于抓包的问题

### ISSUE THREAD

**Issue by gaofengwh** [wfion/unicomSign#1]
不知道项目现在是否还可以运行，我clone了一份在本地，然后修改了json中的phone为自己的手机号，但是url的参数通过charles抓到了很多数据就是没找与url类似的参数，我是在iOS设备上登录时抓的包，找了一下没发现作者的联系方式，就冒昧在这里提了一个问题。

**Comment by changeGood** [comment]
用docker的吧，现在脚本遍地开花~

**Comment by changeGood** [comment]
> 不知道项目现在是否还可以运行，我clone了一份在本地，然后修改了json中的phone为自己的手机号，但是url的参数通过charles抓到了很多数据就是没找与url类似的参数，我是在iOS设备上登录时抓的包，找了一下没发现作者的联系方式，就冒昧在这里提了一个问题。
